import React from 'react';

const About = () => {
  return (
    <div>
      <h3>this is real about page in react router</h3>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit, natus a. Dolores libero rerum eius, iusto nam necessitatibus expedita quod adipisci unde deserunt temporibus facilis, natus quo mollitia reiciendis ipsum magni id porro maiores molestiae nobis! Beatae mollitia fugit quia cumque porro eligendi nostrum quo doloribus cupiditate, pariatur dolor suscipit. A ducimus eos nostrum. Quis, ratione, autem suscipit enim provident quae, non nemo ut quos maxime obcaecati cumque accusantium deleniti. Eligendi dignissimos consectetur omnis totam, labore aliquam eum quod, quis hic exercitationem unde consequatur amet nam qui et. Ea quam ipsum culpa quaerat neque iusto hic error sed suscipit quae? Fugiat tempore illum dolorem iste labore commodi enim alias deserunt mollitia. Obcaecati earum minima excepturi, maxime est veniam a nesciunt eveniet deleniti rem blanditiis minus, impedit beatae ratione veritatis vel aperiam. Libero blanditiis expedita voluptatibus vero doloribus error quam perspiciatis. Quisquam neque reiciendis ullam nemo ad voluptatem, error fugiat eaque placeat sit at rem ipsa. Tempore, obcaecati, in dolorum tempora magnam numquam dolores pariatur, possimus itaque nulla qui sed eveniet officia delectus quasi aliquam recusandae deleniti dicta? Ullam aliquam rerum adipisci similique quis voluptatibus sed, optio mollitia repellendus dolor nihil temporibus eligendi porro beatae rem laudantium repudiandae totam. Expedita cumque modi facere veritatis suscipit deserunt commodi, enim inventore eligendi, ipsam culpa in cupiditate blanditiis ad harum molestias at. Cumque quas iusto harum molestias et! Voluptatibus beatae laudantium, voluptas nemo officiis libero recusandae inventore qui sequi eum ex veniam velit natus dolorem voluptate nulla, fugiat exercitationem, obcaecati placeat modi nihil reprehenderit quae. Porro similique a sequi voluptatibus ex minus architecto reprehenderit esse perferendis tempora quaerat minima, aut neque eos quam laboriosam totam. Harum sint eos libero culpa molestiae inventore fugit perspiciatis. Dolorem labore velit a, suscipit fugit quia vel ex corporis optio sit aspernatur obcaecati rerum quas numquam eligendi totam dolores atque ipsum dignissimos architecto! Facere hic, laboriosam blanditiis dolor quos nihil, libero tione, quod fuga rem, ipsam et. Vel assumenda consequatur ipsum, soluta animi non libero.</p>
    </div>
  );
};

export default About;